# generated files -- trailing whitespace etc. doesn't matter too much for these
exclude: (?x)^(data/.*)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 12e63946db2c5cfcc9030fac21c3883ba88c6ed8 # frozen: 0.38.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 4160603246a6b365d4a2af661c6d71b0a0f50478 # frozen: 26.5.1
    hooks:
      - id: black
  - repo: meta
    hooks:
      - id: check-hooks-apply

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: quarterly
  submodules: false
