name: Check scripts

on:
  push:
  pull_request:

jobs:
  black:
    name: Check formatting with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - run: pip install black
      - run: |
          black --version
          black --check .

  mypy:
    name: Check scripts with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - run: pip install mypy types-requests types-toml pytest
      - run: mypy --strict -p scripts -p tests

  tests:
    name: Run integration and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout typeshed
        uses: actions/checkout@v2
        with:
          repository: python/typeshed
          path: typeshed
      - name: Run tests
        run: |
          pip install pytest toml requests setuptools wheel
          cd main
          python -m pytest tests
