name: Check scripts

on:
  push:
  pull_request:

jobs:
  black:
    name: Check formatting with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: |
          black --version
          black --check .

  mypy:
    name: Check stub_uploader with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: mypy --strict -p stub_uploader -p tests

  tests:
    name: Run integration and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout typeshed
        uses: actions/checkout@v4
        with:
          repository: python/typeshed
          path: typeshed
      - name: Run tests
        run: |
          cd main
          pip install -r requirements.txt
          python -m pytest tests
