name: Force update of some stubs from typeshed to PyPI

on:
  workflow_dispatch:
    inputs:
      distribution:
        description: 'Package name or pattern (Python regexp)'
        required: true

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          path: main
          # Needed to push updates to the uploaded packages list.
          persist-credentials: true
      - name: Setup uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          version: '0.12.10'
          working-directory: main
          python-version: '3.13'
          enable-cache: false
      - name: Checkout typeshed
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          repository: python/typeshed
          path: typeshed
          persist-credentials: false
      - name: Install dependencies
        working-directory: main
        run: uv sync --locked
      - name: Execute build and upload
        env:
          DISTRIBUTION: ${{ github.event.inputs.distribution }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TYPESHED_BOT_API_TOKEN }}
        run: |
          cd main
          uv run --locked python -m stub_uploader.upload_some ../typeshed "$DISTRIBUTION"
          # If we are force uploading packages that were never uploaded, they are added to the list
          if [ -z "$(git status --porcelain)" ]; then
              exit 0;
          fi
          git config user.name github-actions && git config user.email github-actions@github.com
          git add . && git commit -m "Update uploaded packages list" && git push
