name: Test PyPI API token

on:
  # Only triggered manually (for debugging/integration testing).
  workflow_dispatch:
    inputs:
      increment:
        description: 'Package minor version'
        required: true
        default: 0

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      with:
        persist-credentials: false
    - name: Setup uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      with:
        version: '0.12.10'
        python-version: '3.13'
        enable-cache: false
    - name: Install dependencies
      run: uv sync --locked
    # This workflow specifically tests API-token authentication.
    - name: Build and publish  # zizmor: ignore[use-trusted-publishing]
      env:
        PACKAGE_VERSION_INCREMENT: ${{ github.event.inputs.increment }}
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TYPESHED_BOT_API_TOKEN }}
      run: |
        cd data/empty_package
        uv run --locked python -m build --wheel --no-isolation
        uv run --locked twine upload dist/*
