name: Test PyPI API token

on:
  # Only triggered manually (for debugging/integration testing).
  workflow_dispatch:
    inputs:
      increment:
        description: 'Package minor version'
        required: true
        default: 0

env:
  FORCE_COLOR: 1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TYPESHED_BOT_API_TOKEN }}
      run: |
        cd data/empty_package
        PACKAGE_VERSION_INCREMENT=${{ github.event.inputs.increment }} python -m build --wheel --no-isolation
        twine upload dist/*
